# Project information
site_name: Analysis Docs
site_description: 'Analysis Docs'
site_author: 'Timothe'
site_url: 'https://Freelymovinganalysis.github.io/.github/index.html'

# Copyright
copyright: '&copy; 2022 Shulz Lab'

# Repository
repo_name: '.github'
repo_url: 'https://github.com/FreelyMovingAnalysis/.github'
edit_uri: ''

use_directory_urls: false

docs_dir: 'docs'

theme: 
    name : material
    palette:
      - scheme: slate
        primary: deep orange
        accent: teal
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
      - scheme: default 
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
        
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.top
    highlightjs : true
    hljs_languages :
        - python
        - c++
        - c
        - html
        - css
        - cmd

plugins:
    - search      
   
markdown_extensions:
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - attr_list
    - def_list
 
nav:
    - Home: index.md
    - Code:
        - pLabAna: 'pLabAna/main.md'

